apiVersion: v1
kind: ReplicationController
metadata:
  name: titofe
  labels:
    name: tito-fe
    version: "latest"
    app: tito
    tiers: tito-fe
    stage: prod
spec:
  replicas: 1 
  selector:
    type: tito-fe
    version: v1
  template:
    metadata:
      labels:
        app: tito
        type: tito-fe
        version: v1
        tiers: tito-fe
    spec:
      containers:
        - name: tito
          image: harbor.pks-reg.gv/pksparis/tito-fe:latest
          ports:
          - containerPort: 80
          env:
          - name: TITO_SQL_SERVICE_SERVICE_HOST
            value: tito-sql-service
          - name: TITO_VERSION
            value: V1.9.2
      imagePullSecrets:
        - name: regsecret
